jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        run: echo "Building the application"

  test:
    runs-on: ubuntu-latest
    needs: build # Test runs only after build is successful
    steps:
      - name: Run tests
        run: echo "Running tests"

  deploy: 
    runs-on: ubuntu-latest
    needs: test # Deploy runs only after test is successful
    steps: 
      - name: Deploy to production
      run: echo "Deploying to production"
      
